# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Build with Maven
      env:
        TOKEN: ${{ secrets.TOKEN }}
        USERNAME: ${ env.USERNAME } 
      run: mvn -B package --settings settings.xml --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      env:
          TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${ env.USERNAME } 
      run: mvn deploy -s settings.xml
